export const CompetitionStage = {
    REGISTRATION_OPENED: 0,
    REGISTRATION_CLOSED: 1,
    PRELIMINARY_CASE_RELEASED: 2,
    PRELIMINARY_SUBMISSION_DEADLINE: 3,
    PRELIMINARY_STAGE_CLOSED: 4,
    SEMIFINAL_RESULTS_ANNOUNCED: 5,
    SEMIFINAL_CASE_RELEASED: 6,
    SEMIFINAL_SUBMISSION_DEADLINE: 7,
    SEMIFINAL_STAGE_CLOSED: 8,
    FINAL_RESULTS_ANNOUNCED: 9
};