language: generic

deploy:
  - provider: gae
    keyfile: bistleague-beta-deployment.json
    project: bist-league-beta
    config: app-staging.yaml
    skip_cleanup: true
    on:
      branch: staging
  - provider: gae
    keyfile: bistleague-prod-deployment.json
    project: bist-league
    config: app-prod.yaml
    skip_cleanup: true
    on:
      branch: production

before_install:
- openssl aes-256-cbc -K $encrypted_6c8cfcc0c1db_key -iv $encrypted_6c8cfcc0c1db_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
