deploy:
- provider: gae
  keyfile: bistleague-beta-deployment.json
  project: bist-league-beta
  config: app-staging.yaml
before_install:
- openssl aes-256-cbc -K $encrypted_6c8cfcc0c1db_key -iv $encrypted_6c8cfcc0c1db_iv
  -in bistleague-beta-deployment.json.enc -out bistleague-beta-deployment.json -d
- openssl aes-256-cbc -K $encrypted_6c8cfcc0c1db_key -iv $encrypted_6c8cfcc0c1db_iv
  -in app-staging.yaml.enc -out app-staging.yaml -d
